### ISSUE TITLE
Not working on Production environment

### ISSUE THREAD

**Issue by andrii-bodnar** [ionic-team/stencil-helmet#27]
Hi there!

The library successfully updates all the metatags if it's running on the dev environment. But when it's running on Production - metatags are not updated.

The `@stencil/helmet` dependency is located in the "dependencies" object of the *package.json* file. Version - 0.3.2.

Any suggestions on what is wrong? 

Thank you!

**Comment by andrii-bodnar** [comment]
Updating to the 0.3.3-0 version fixed my issue but there are appeared some unwanted console logs. Fixed it in #28

**Comment by rwaskiewicz** [comment]
Closing this issue as it appears to be fixed [per the issue author.](https://github.com/ionic-team/stencil-helmet/issues/27#issuecomment-1082727365)
