### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by DominicBoettger** [ionic-team/stencil-helmet#5]
Can you please update the version to be compatible with the latest stencil version?
The version currently released on npmjs creates build errors with the childitems. I think the latest commits will fix this.

**Comment by DominicBoettger** [comment]
This is important as the current npm version is incompatible with stencil versions >0.11.4. Meanwhile i create a fork...

**Comment by badpenguin** [comment]
> This is important as the current npm version is incompatible with stencil versions >0.11.4. Meanwhile i create a fork...

I have  tried your version with npm install @inspirationlabs/helmet
it compiles
but the headers will not change not a runtime, not a prerendering.

**Comment by DominicBoettger** [comment]
Since the upgrade of stencil one the project stopped working at all.
